TallerMecanico/API/TallerMecanico/TallerMecanico/Controllers/AutomovilController.cs
using Microsoft.AspNetCore.Mvc;
using TallerMecanico.Datos;
using TallerMecanico.Models;

namespace TallerMecanico.Controllers
{
    public class AutomovilController : Controller
    {
        AutomovilDatos _AutomovilDatos = new AutomovilDatos();

        public IActionResult Listar()
        {
            //La vista muestra una lista de automóviles
            var oLista = _AutomovilDatos.Listar();
            return View(oLista);
        }

        public IActionResult Agregar()
        {
            //Devuelve la vista
            return View();
        }

        [HttpPost]
        public string Agregar(AutomovilModel Automovil)
        {
            //Recibe un automotor para guardarlo en la base
            var respuesta = _AutomovilDatos.Agregar(Automovil);
            return respuesta;
        }

        public IActionResult Editar(int IdAutomovil)
        {
            var oAutomovil = _AutomovilDatos.Obtener(IdAutomovil);

            return View(oAutomovil);
        }

        [HttpPost]
        public string Editar(AutomovilModel Automovil)
        {
            //Recibe un automovil para editarlo en la base
            string respuesta = "datos";  //Si el formulario no es válido se informa al usuario
            if (ModelState.IsValid)
                respuesta = _AutomovilDatos.Editar(Automovil); //Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }

        public IActionResult Eliminar(int IdAutomovil)
        {
            var oAutomovil = _AutomovilDatos.Obtener(IdAutomovil);
            if (oAutomovil == null)
            {
                return NotFound();
            }
            return View(oAutomovil);
        }

        [HttpPost]
        public string Eliminar(AutomovilModel oAutomovil)
        {
            //Recibe un automovil para settearle la fecha de baja en la base
            var respuesta = _AutomovilDatos.Eliminar(oAutomovil.IdAutomovil); //Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }
    }
}

TallerMecanico/API/TallerMecanico/TallerMecanico/Controllers/MotocicletaController.cs
using Microsoft.AspNetCore.Mvc;
using TallerMecanico.Datos;
using TallerMecanico.Models;

namespace TallerMecanico.Controllers
{
    public class MotocicletaController : Controller
    {
        MotocicletaDatos _MotocicletaDatos = new MotocicletaDatos();

        public IActionResult Listar()
        {
            // La vista muestra una lista de motocicletas
            var oLista = _MotocicletaDatos.Listar();
            return View(oLista);
        }

        public IActionResult Agregar()
        {
            // Devuelve la vista
            return View();
        }

        [HttpPost]
        public string Agregar(MotocicletaModel oMotocicleta)
        {
            // Recibe una motocicleta para guardarla en la base
            var respuesta = _MotocicletaDatos.Agregar(oMotocicleta);
            return respuesta;
        }

        public IActionResult Editar(int IdMotocicleta)
        {
            var oMotocicleta = _MotocicletaDatos.Obtener(IdMotocicleta);
            return View(oMotocicleta);
        }

        [HttpPost]
        public string Editar(MotocicletaModel oMotocicleta)
        {
            // Recibe una motocicleta para editarla en la base
            string respuesta = "datos";  // Si el formulario no es válido se informa al usuario
            if (ModelState.IsValid)
                respuesta = _MotocicletaDatos.Editar(oMotocicleta); // Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }

        public IActionResult Eliminar(int IdMotocicleta)
        {
            var oMotocicleta = _MotocicletaDatos.Obtener(IdMotocicleta);
            if (oMotocicleta == null)
            {
                return NotFound();
            }
            return View(oMotocicleta);
        }

        [HttpPost]
        public string Eliminar(MotocicletaModel oMotocicleta)
        {
            // Recibe una motocicleta para settearle la fecha de baja en la base
            var respuesta = _MotocicletaDatos.Eliminar(oMotocicleta.IdMotocicleta); // Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }
    }
}

TallerMecanico/API/TallerMecanico/TallerMecanico/Controllers/PresupuestoController.cs
using Microsoft.AspNetCore.Mvc;
using TallerMecanico.Datos;
using TallerMecanico.Models;
using TallerMecanico.Models.DTOs;

namespace TallerMecanico.Controllers
{
    public class PresupuestoController : Controller
    {
        private readonly PresupuestoDatos _presupuestoDatos;

        public PresupuestoController()
        {
            _presupuestoDatos = new PresupuestoDatos();
        }

        public IActionResult Listar()
        {
            var presupuestos = _presupuestoDatos.Listar();
            return View(presupuestos);
        }

        public List<VehiculoDto> LlenaComboVehiculos()
        {
            var respuesta = _presupuestoDatos.LlenaComboVehiculos();
            return respuesta;
        }
        public List<VehiculoDto> LlenaComboVehiculosEditar()
        {
            var respuesta = _presupuestoDatos.LlenaComboVehiculosEditar();
            return respuesta;
        }

        public IActionResult Obtener(int id)
        {
            var presupuesto = _presupuestoDatos.Obtener(id);
            if (presupuesto == null)
            {
                return NotFound();
            }
            return View(presupuesto);
        }

        public IActionResult Agregar()
        {
            //Devuelve la vista
            return View();
        }

        [HttpPost]
        public string Agregar(PresupuestoModel presupuesto)
        {
            //Recibe un presupuesto para guardarlo en la base
            var respuesta = _presupuestoDatos.Agregar(presupuesto);
            return respuesta;
        }

        public IActionResult Editar(int IdPresupuesto)
        {
            var oPresupuesto = _presupuestoDatos.Obtener(IdPresupuesto);

            return View(oPresupuesto);
        }

        [HttpPost]
        public string Editar(PresupuestoModel oPresupuesto)
        {
            //Recibe un presupuesto para editarlo en la base
            string respuesta = "datos";  //Si el formulario no es válido se informa al usuario
            if (ModelState.IsValid)
                respuesta = _presupuestoDatos.Editar(oPresupuesto); //Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }

        public IActionResult Eliminar(int IdPresupuesto)
        {
            var oPresupuesto = _presupuestoDatos.Obtener(IdPresupuesto);
            if (oPresupuesto == null)
            {
                return NotFound();
            }
            return View(oPresupuesto);
        }

        [HttpPost]
        public string Eliminar(PresupuestoModel oPresupuesto)
        {
            //Recibe un presupuesto para settearle la fecha de baja en la base
            var respuesta = _presupuestoDatos.Eliminar(oPresupuesto.IdPresupuesto); //Este método puede devolver un error o ""(Correcto)
            return respuesta;
        }
    }
}

TallerMecanico/API/TallerMecanico/TallerMecanico/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Mvc;
using TallerMecanico.Datos;
using TallerMecanico.Models;
using TallerMecanico.Models.DTOs;

namespace TallerMecanico.Controllers
{
    public class ReporteController : Controller
    {
        private readonly ReporteDatos _ReporteDatos = new ReporteDatos();

        public IActionResult Listar()
        {
            //Devuelve la vista
            return View();
        }

        public List<Reporte1DTO> Reporte1()
        {
            var oLista = _ReporteDatos.Reporte1();

            return oLista;
        }

        public List<Reporte2DTO> Reporte2()
        {
            var oLista = _ReporteDatos.Reporte2();

            return oLista;
        }

        public List<Reporte3DTO> Reporte3()
        {
            var oLista = _ReporteDatos.Reporte3();

            return oLista;
        }
    }
}

TallerMecanico/API/TallerMecanico/TallerMecanico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TallerMecanico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TallerMecanico.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TallerMecanico</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuesto" asp-action="Listar">Presupuesto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Automovil" asp-action="Listar">Automoviles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Motocicleta" asp-action="Listar">Motocicletas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reporte" asp-action="Listar">Reportes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TallerMecanico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>